spring.application.name=auth-api
jwt.secret=this-is-a-very-long-secret-key-for-jwt-signing-please-change-it-in-prod
jwt.expiration=3600000
spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8082
spring.jpa.hibernate.ddl-auto=update
internal.token=${INTERNAL_TOKEN:local-dev-secret}
data-api.url=${DATA_API_URL:http://localhost:8081}